<?php

/**
 * @file
 * Install, update and uninstall functions for the nobots module.
 */

/**
 * Implements hook_install().
 */
function nobots_install() {
  variable_set('nobots', 'TRUE');
}

/**
 * Implements hook_update_N().
 *
 * Set the nobots variable to TRUE.
 */
function nobots_update_7201(&$sandbox) {
  variable_set('nobots', 'TRUE');
}

/**
 * Implements hook_uninstall().
 */
function nobots_uninstall() {
  variable_del('nobots');
}
